### ISSUE TITLE
open

### ISSUE THREAD

**Issue by Kizuno18** [m-jishnu/alt-app-installer#30]
hello, how to open multiple instances of the same app?

**Comment by m-jishnu** [comment]
you would need to create 2 copies of alt app installer folder and launch "alt app installer.exe" from both of the folders this way you can create multiple instance of the app. you can also try double clicking the alt app installer from same folder twice this will launch two instances of the app but if you try downloading the same app from both the instances simultaneously it can cause errors since both are sharing resources. but if the both of the are downloading different apps it shouldn't cause any issue but some app do have common dependency so there is a chance of getting errors, so I would recommend creating 2 copies of the alt  app installer then running them.
