### ISSUE TITLE
One Note and Teams shows "No Data Found"

### ISSUE THREAD

**Issue by naxl** [m-jishnu/alt-app-installer#37]
Hey this app works flawless for every other app, I tried downloading "OneNote and "Teams" using this app but it shows an error "No Data Found",To your surprise, I was actually looking for an alternative to the store.adguard.net proxy as these two apps are not being found there as well, I think microsoft found a way to not list new apps on their server, Please let me know if you can find a fix to this, I desperately need UWP version of these apps and the hunt for them seems exhausting!! (I don't have store in my PC, I wanna live like this :P)

Logs :

[python logs] 
[03-07-2023 19:16:57]

Traceback (most recent call last):
  File "maingui.py", line 91, in run
  File "maingui.py", line 261, in <lambda>
  File "url_gen.py", line 33, in url_generator
Exception: No Data Found: --> [You Selected Wrong Page, Try Again!]
----------------------------------------------------------------------------------
[python logs] 
[03-07-2023 19:17:42]

Traceback (most recent call last):
  File "maingui.py", line 91, in run
  File "maingui.py", line 261, in <lambda>
  File "url_gen.py", line 33, in url_generator
Exception: No Data Found: --> [You Selected Wrong Page, Try Again!]
----------------------------------------------------------------------------------

**Comment by m-jishnu** [comment]
hello, teams and one note doesn't have ump apps it seems ms store now also allows non ump apps in the store and teams and one note are not ump apps you can install and uninstall them like normal apps, alt app installer can only download and install ump apps since it doesn't have the necessary api endpoints to get normal apps from store.  i used to use store.adguard.net api but it was unreliable sometimes so i switched to direct link generation via storelib it directly calls the ms apis and gets the apps but it also only works for ump apps others doesn't show up.

**Comment by m-jishnu** [comment]
hello just to let you know that i have added the function to download non-ump files too now, the app can download one note and teams though note download can take time since the ms server doesn't allow multi-threaded download.

**Comment by naxl** [comment]
Yes! Figured about that new ms redirection for packages through store. Forgot to update it here!, Thanks for this update as well tho! Really appreciate it. : )
