### ISSUE TITLE
Some Feature Request

### ISSUE THREAD

**Issue by FaithfulObserver** [m-jishnu/alt-app-installer#42]
Hi, this is the first time I have found an application that can download Microsoft Store apps purely directly using the MS-Store-API and not via a third party website. For those who are security paranoid like me, your Alt App Installer is truly like a send from heaven, so much potential. :D

Do you have plans to add the following features?
1. Download the app only (without installing).
2. Each downloaded app is placed in a separate folder.
3. Ability to use the command line, error level output that can be captured in a batch script, and can run silently.

**Comment by m-jishnu** [comment]
hello, glad to bear it was helpful

1 and 2 should be easy to implement the 3 one need some work. so i will try to implement the 1 and 2 

1. for the 1st suggestion i think we can implement it as a Toggle in option by default it will download and install the app but if the toggle is enabled it will only download the app

2. i am assuming that by each app having their own folder you mean like for terminal app there should be a folder called terminal and inside it should be the app installer and its dependencies.
[the reason i implemented all apps to be downloaded into same folder was cause many app share the same dependency so instead of downloading the same dependency over and over again it could use the already downloaded
 dependency thus saving bandwidth and space]

3. since this is a gui app which uses pyqt, we would need to create wrapper for each functionality like install,download etc. and the final should look something like "altinstaller --install app.appx" to install an app

**Comment by FaithfulObserver** [comment]
For point 2, I can see your reasoning.

My reason for point 2 is that I see the folder not solely as a cache but as a repository for a collection of installer packages that can be used for purposes other than the original alt-app-installer designation. For example, repackaging in an installer bundle or for mass deployment purposes.

Maybe it would be better if the original cache folder remained but added the function of generating a package folder for repository purposes where the installer package and its dependencies are combined.

**Comment by m-jishnu** [comment]
As of v2.6.6 i have implemented the 1st (options --> advanced --> download mode) and 2nd (options --> advanced --> dedicated folder) feature  the 3rd one isn't that simple and would need some work. i might implement it in future or if someone is willing to do it feel free to make a PR.

**Comment by FaithfulObserver** [comment]
Thank you very much for v2.6.6.

Unfortunately, the analysis results from Hybrid-Analysis.com don't look good:
https://tinyurl.com/ys33dqxo

**Comment by m-jishnu** [comment]
> Thank you very much for v2.6.6.
> 
> Unfortunately, the analysis results from Hybrid-Analysis.com don't look good:
> https://tinyurl.com/ys33dqxo
> 

No malware analysis tool can properly tell if a file is safe or not it just check for patterns and gives an assumption unless the file has been tested and reported as malicious moreover most day one exploits are never detected by these so called detectors. if you really want to see if its malicious or not check the source code

since the executable i gave is not digitally signed and wasn't downloaded much its showing false positive. the executable is just a sfx which contains the compiled python code of the app it was created using pyinstaller 

but if you are paranoid or suspicious about the executable feel free to build the app from source.

**Comment by drogga** [comment]
_Sorry to bother, but since I also have a feature request and found this one, I decided to comment here instead, please tell me if this is not ok and/or problematic and I will delete my (this) comment ;)_

Drag 'n Drop installation file(s) to the program's window.

<details><summary>A bit off-topic</summary> - I'm currently trying to make this `https://apps.microsoft.com/detail/9MZF9DMHNH3P` work, but, no success for now and I've installed the requirements already, even before trying with "Alt App Installer".

> **This app can't open**
> There’s a problem with Notification Logger. Reinstall the application from its original install location or contact your administrator.</details>

**Comment by m-jishnu** [comment]
> _Sorry to bother, but since I also have a feature request and found this one, I decided to comment here instead, please tell me if this is not ok and/or problematic and I will delete my (this) comment ;)_
> 
> Drag 'n Drop installation file(s) to the program's window.
> 
> <details><summary>A bit off-topic</summary> - I'm currently trying to make this `https://apps.microsoft.com/detail/9MZF9DMHNH3P` work, but, no success for now and I've installed the requirements already, even before trying with "Alt App Installer".
> 
> > **This app can't open**
> > There’s a problem with Notification Logger. Reinstall the application from its original install location or contact your administrator.</details>

hello, so you want a feature where by dragging the appx/msix file (installation files) alt app installer installs them right. if that's what you want have you tried options --> install from file, also it would have been better to open this feature request as a new issue since its easier to track that way. regarding the case where you are not able to install the app, message me on discord it would be easier to help there.

**Comment by m-jishnu** [comment]
These features need a lot of work currently i am not planning on implementing them but i might do in feature but if you can be sure to create a pr I will merge it.

if you want check [v1](https://github.com/m-jishnu/alt-app-installer/releases/tag/v1.0.1) of the app it only have installation

**Comment by drogga** [comment]
I would love to create a PR, but unfortunately I'm not a coder, I only know 2 human languages, I thing or 2 about android packages reverse engineering, but that doesn't mean I know Java/Kotlin or Smali, so the fact that I'm on GH doesn't mean that I'm a programmer, the same for may others as well. Sure, I might be a Collaborator in 1 android app repo, but that's just to be able to manage the issue tickets and discussions.

TBH, I'm not a fan of MS store and the software (including games and whatnot) it provides, also I don't have much use of this program either, but I decided to try it for the first time and it wasn't able to do what I expected it to be able to, but I've decided to share some feedback anyway..., btw I've uninstalled the MS store app, because it's annoying and downloads and updates things I don't want it to and I've set the preference to not update automatically, but it didn't respect it, and guess what - W.11 still DLed Widgets related garbage on my system, even with System Updates paused for 10 years ahead (regedit) and MS Store not being installed.

I'm perfectly well aware that that it's because the app is paid and I mentioned in my E-mail that I think you should mention that those won't work here - if not all paid, then at least some if not most won't work with or without your AAI program, or even by installing them from the PowerShell, but you haven't replied there. If you can do something to help me make the "Notification Logger" work, I guess it would require modifying it and you could've done that in an E-Mail if you wanted to at all, so IDK why you insist that much on that Discord and how will you better help me there, because no troubleshooting is required in my opinion, as this is not a problem with my configuration, but the fact that paid apps have license, install source and whatnot checks.
Sure, I will create a Discord account if I have to, at least it doesn't require a phone number like TG, but I won't be online all the time, but only launch it when I want to, because my phone is offline (no Wi-Fi or data connected) when I'm not using it, so I will be slow at responding.

Sorry about the rant.

**Comment by m-jishnu** [comment]
hello, sorry if you misinterpreted what i meant was if you are able to you can implement it. i have replied to your email too i didn't check the mail so didn't notice it. as for paid apps you are able to download some and some does work but i don't give much priority to it as this is not what the app is for. i won't be spending any time on figuring out endpoints for paid apps/games or implementing them the app is for providing alternate for free ms store apps

if you want much cleaner win experience i suggest you try building  windows using tiny10builder or similar tool and remove all the clutter you dont need also check out Christitus debloat tool its also a great app with lot of features you would like disabling updates etc

regarding discord the main reason i said so is because its easier to chat there compared to email or GH especially while using a phone. that's said if you are uncomfortable with discord feel free to ask on GH or on mail i will help with the best of my abilities
